apiVersion: v1
kind: Namespace
metadata:
  name: customer-intelligence
  labels:
    app.kubernetes.io/name: customer-intelligence-platform
    app.kubernetes.io/managed-by: github-actions
    environment: production
